-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "stripeCustomerId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "subscriptionStatus" TEXT DEFAULT 'free';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "subscriptionId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "subscriptionEndDate" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "provider" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "onboardingCompleted" BOOLEAN DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "emailToken" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "emailTokenExpiry" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "emailVerified" TIMESTAMP(3);

-- AddUniqueConstraint
ALTER TABLE "User" ADD CONSTRAINT IF NOT EXISTS "User_stripeCustomerId_key" UNIQUE ("stripeCustomerId");
ALTER TABLE "User" ADD CONSTRAINT IF NOT EXISTS "User_emailToken_key" UNIQUE ("emailToken"); 